syntax = syntax rule, {syntax rule};
syntax rule = meta identifier, defining symbol, definitions list, terminator symbol;
definitions list = single definition, {definition separator symbol, single definition};
single definition = syntactic term, {concatenate symbol, syntactic term};
syntactic term = syntactic factor, [except symbol, syntactic exception];


syntactic factor = [integer, repetition symbol], syntactic primary;
syntactic primary
= optional sequence
| repeated sequence
| grouped sequence
| meta identifier
| terminal string
| special sequence
| empty sequence;